name: Frontend pull request
on:
  pull_request:
    branches:
      - main
    paths:
      - frontend
jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Fetch code
        uses: actions/checkout@v3
      - name: Install Node
        uses: actions/setup-node@v3
        with:
          node-version: "19"
      - name: Install Node modules
        workin-directory: ./frontend
        run: npm install --include=devDependencies
      - name: Run tests for frontend
        working-directory: ./frontend
        run: npm run test:run